AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/LineLength:
  Max: 120

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Metrics:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/NegatedIf:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false
